[project]
name = "insta-salesbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fast-agent-mcp>=0.2.34",
    "fastmcp>=2.9.0",
    "instagrapi>=2.1.5",
    "pillow>=11.2.1",
]
