# Model string takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
#
# Can be overriden with a command line switch --model=<model>, or within the Agent decorator.
# Check here for current details: https://fast-agent.ai/models/
default_model: "azure.gpt-4.1-nano"

azure:
  azure_deployment: "gpt-4.1-nano"
  api_version: "2025-01-01-preview" # Optional

# set the default model for fast-agent below:
# default_model: gpt-4.1-nano

# Logging and Console Configuration:
logger:
  # Switched off to avoid cluttering the console
  progress_display: false

  # Show chat User/Assistant messages on the console
  show_chat: true
  # Show tool calls on the console
  show_tools: true
  # Truncate long tool responses on the console
  truncate_tools: true

# MCP Servers
mcp:
  servers:
    insta_mcp:
      transport: http
      url: http://localhost:4200/insta-mcp
    bakery_mcp:
      transport: http
      url: http://localhost:4300/bakery-mcp
    agent_bakery_assistant:
      transport: sse
      url: http://localhost:4400/sse
